import { javascript, html5, css3, typescript, python, node, express, react, redux, flask, django, jwt, npm, mysql, mongodb, sequelize, jest, cypress, mocha, chai, rtl, pytest, git, githubPages, docker, vscode, insomnia, eslint, trello, linux } from "./centralIconsFile";

export const stacksArray = [
    { img: javascript, alt: "javascript" },
    { img: html5, alt: "html5" },
    { img: css3, alt: "css3" },
    { img: typescript, alt: "typescript" },
    { img: python, alt: "python" },
    { img: node, alt: "node.js" },
    { img: express, alt: "express.js" },
    { img: react, alt: "react" },
    { img: redux, alt: "redux" },
    { img: flask, alt: "flask" },
    { img: django, alt: "django" },
    { img: jwt, alt: "jwt" },
    { img: npm, alt: "npm" },
    { img: mysql, alt: "mysql" },
    { img: mongodb, alt: "mongodb" },
    { img: sequelize, alt: "sequelize" },
    { img: jest, alt: "jest" },
    { img: cypress, alt: "cypress" },
    { img: mocha, alt: "mocha" },
    { img: chai, alt: "chai" },
    { img: rtl, alt: "rtl" },
    { img: pytest, alt: "pytest" },
    { img: git, alt: "git" },
    { img: githubPages, alt: "github pages" },
    { img: docker, alt: "docker" },
    { img: vscode, alt: "vscode" },
    { img: insomnia, alt: "insomnia" },
    { img: eslint, alt: "eslint" },
    { img: trello, alt: "trello" },
    { img: linux, alt: "linux" },
  ];